name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone private action repository
        env:
          ACTIONS_PAT: ${{ secrets.PROPOSAL_TEST }}
        run: |
          git clone https://$ACTIONS_PAT@github.com/openteamsinc/repos-proposal.git .github/actions/repos-proposal

      - name: Run REPOS Proposal Publisher
        uses: ./github/actions/repos-proposal
        with:
          token: ${{ secrets.PROPOSAL_TEST }}