name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone private repository
        run: |
          git clone https://x-access-token:${{ secrets.PROPOSAL_TEST }}@github.com/openteamsinc/repos-proposal.git
        env:
          GIT_TERMINAL_PROMPT: 0

      - name: Run REPOS Proposal Publisher
        run: |
          cd repos-proposal
          ./repos-proposal --token ${{ secrets.PROPOSAL_TEST }}
