name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout private action
        run: |
          git clone https://$PAT@github.com/openteamsinc/repos-proposal.git .github/actions/repos-proposal
        env:
          PAT: ${{ secrets.PROPOSAL_TEST }}

      - name: Run REPOS Proposal Publisher
        uses: ./github/actions/repos-proposal
        with:
          token: ${{ secrets.GPROPOSAL_TEST }}
