name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout private action repository
        uses: actions/checkout@v3
        with:
          repository: openteamsinc/repos-proposal
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      # Run the action from the private repository
      - name: Run REPOS Proposal Publisher
        run: ./repos-proposal
