name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone private action repository
        run: |
          echo "Cloning private repository..."
          git clone https://${{ secrets.PROPOSAL_TEST }}@github.com/openteamsinc/repos-proposal.git .github/actions/repos-proposal

      - name: Run REPOS Proposal Publisher
        uses: ./github/actions/repos-proposal
        with:
          token: ${{ secrets.PROPOSAL_TEST }}
