name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Checkout private action repository
      - name: Checkout private action repository
        uses: actions/checkout@v3
        with:
          repository: openteamsinc/repos-proposal
          ref: dev
          token: ${{ secrets.GITHUB_TOKEN }}

      # Run REPOS Proposal Publisher
      - name: Run REPOS Proposal Publisher
        run: |
          cd repos-proposal
          ./repos-proposal --token ${{ secrets.GITHUB_TOKEN }}