name: REPOS Proposal Publisher

on:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run REPOS Proposal Publisher
      - name: Run REPOS Proposal Publisher
        uses: openteamsinc/repos-proposal@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}